#PyTorch Programs

In [1]:
import torch
import numpy as np
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
c= a+b
print(c)
print(torch.dot(a,b))
print(a*b)

tensor([5., 7., 9.])
tensor(32.)
tensor([ 4., 10., 18.])


In [2]:
x=torch.arange(12)
print(x)
x=x.view(3,4)
print("reshaped", x.view(3,4))


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
reshaped tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [3]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [4]:
#Differentiation in the workbook.
x=torch.tensor(2.0, requires_grad=True)

y=x**3+2*x+1
y.backward()
print("Gradient 2", x.grad)

Gradient 2 tensor(14.)


In [5]:
import torch  # You forgot to import torch

# Define the shape of the tensor
shape = (3, 3)
rand_tensor = torch.rand(shape)

Enrl_tensor = torch.ones(2,2)
Name_tensor = torch.zeros(shape)

# Print tensors
print(f"Random Tensor: \n{rand_tensor}\n")
print(f"Enrl Tensor: \n{Enrl_tensor}\n")
print(f"Name Tensor: \n{Name_tensor}\n")


Random Tensor: 
tensor([[0.7807, 0.6342, 0.3712],
        [0.8296, 0.7948, 0.4104],
        [0.1881, 0.2509, 0.4543]])

Enrl Tensor: 
tensor([[1., 1.],
        [1., 1.]])

Name Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])



In [6]:
tensor=torch.ones(4,4)
print(f"First row:{tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[1,:]
print(tensor)

First row:tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [24]:
import torch

# Create a sample tensor
tensor = torch.randn(3, 4)  # 3x4 matrix

# ------------------ Matrix Multiplication ------------------ #
# Method 1: Using @ operator (matrix multiplication)
y1 = tensor @ tensor.T  # Result shape: [3, 3]

# Method 2: Using matmul
y2 = tensor.matmul(tensor.T)  # Result shape: [3, 3]

# Method 3: Using matmul with out parameter
y3 = torch.empty(tensor.size(0), tensor.size(0))  # Create empty tensor with shape [3, 3]
torch.matmul(tensor, tensor.T, out=y3)

# ------------------ Element-wise Multiplication ------------------ #
# Method 1: Using * operator
z1 = tensor * tensor

# Method 2: Using mul()
z2 = tensor.mul(tensor)

# Method 3: Using mul() with out parameter
z3 = torch.empty_like(tensor)  # Same shape as original tensor [3, 4]
torch.mul(tensor, tensor, out=z3)

# Print results to verify
print("Matrix multiplication (y1):\n", y1)
print("Matrix multiplication (y2):\n", y2)
print("Matrix multiplication (y3):\n", y3)
print("Element-wise multiplication (z1):\n", z1)
print("Element-wise multiplication (z2):\n", z2)
print("Element-wise multiplication (z3):\n", z3)


Matrix multiplication (y1):
 tensor([[ 3.3294, -3.2385, -2.3453],
        [-3.2385,  6.1229,  0.8175],
        [-2.3453,  0.8175,  3.1526]])
Matrix multiplication (y2):
 tensor([[ 3.3294, -3.2385, -2.3453],
        [-3.2385,  6.1229,  0.8175],
        [-2.3453,  0.8175,  3.1526]])
Matrix multiplication (y3):
 tensor([[ 3.3294, -3.2385, -2.3453],
        [-3.2385,  6.1229,  0.8175],
        [-2.3453,  0.8175,  3.1526]])
Element-wise multiplication (z1):
 tensor([[4.1871e-01, 1.7351e+00, 6.3979e-01, 5.3581e-01],
        [3.0309e+00, 2.4543e+00, 2.5543e-01, 3.8228e-01],
        [1.4320e-01, 4.0636e-01, 2.6015e+00, 1.6107e-03]])
Element-wise multiplication (z2):
 tensor([[4.1871e-01, 1.7351e+00, 6.3979e-01, 5.3581e-01],
        [3.0309e+00, 2.4543e+00, 2.5543e-01, 3.8228e-01],
        [1.4320e-01, 4.0636e-01, 2.6015e+00, 1.6107e-03]])
Element-wise multiplication (z3):
 tensor([[4.1871e-01, 1.7351e+00, 6.3979e-01, 5.3581e-01],
        [3.0309e+00, 2.4543e+00, 2.5543e-01, 3.8228e-01],
      

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

<!-- hasdafhj -->

In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
import numpy as np

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

#Scikit Learn Programs

*Decision Tree*

In [ ]:
from sklearn import tree
X = [[0, 0], [1, 1]]
Y = [0, 1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)
#taking 2 array inputs

In [ ]:
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
X, y = iris.data, iris.target
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, y)

In [ ]:
from sklearn import tree
X = [[0, 0], [2, 2]]
y = [0.5, 2.5]
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X, y)
clf.predict([[1, 1]])

In [ ]:
import graphviz
dot_data = tree.export_graphviz(clf, out_file=None)
graph = graphviz.Source(dot_data)
graph.render("iris")

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text
iris = load_iris()
decision_tree = DecisionTreeClassifier(random_state=0, max_depth=2)
decision_tree = decision_tree.fit(iris.data, iris.target)
r = export_text(decision_tree, feature_names=iris['feature_names'])
print(r)

In [ ]:
from sklearn import tree
X = [[0, 0], [2, 2]]
y = [0.5, 2.5]
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X, y)
clf.predict([[1, 1]])

In [ ]:
#Threshold splitter to split the missing value
from sklearn.tree import DecisionTreeClassifier
import numpy as np

X = np.array([0, 1, 6, np.nan]).reshape(-1, 1)
y = [0, 0, 1, 1]

tree = DecisionTreeClassifier(random_state=0).fit(X, y)
tree.predict(X)

In [ ]:
#placing Mission value
from sklearn.tree import DecisionTreeClassifier
import numpy as np

X = np.array([np.nan, -1, np.nan, 1]).reshape(-1, 1)
y = [0, 0, 1, 1]

tree = DecisionTreeClassifier(random_state=0).fit(X, y)

X_test = np.array([np.nan]).reshape(-1, 1)
tree.predict(X_test)

In [ ]:
#missing value mapping to the child
from sklearn.tree import DecisionTreeClassifier
import numpy as np

X = np.array([np.nan, -1, np.nan, 1]).reshape(-1, 1)
y = [0, 0, 1, 1]

tree = DecisionTreeClassifier(random_state=0).fit(X, y)

X_test = np.array([np.nan]).reshape(-1, 1)
tree.predict(X_test)

*SVM*

In [ ]:
# Import libraries
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
# Load dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target


In [ ]:
# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [ ]:
# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
# Train the SVM classifier
svm_model = SVC(kernel='linear')  # You can try 'rbf', 'poly', or 'sigmoid'
svm_model.fit(X_train, y_train)


In [ ]:
# Predict on test set
y_pred = svm_model.predict(X_test)


In [ ]:
# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


In [ ]:
# Visualize confusion matrix
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, cmap="Blues", fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()


*Logistic Regression*

In [ ]:
# Import libraries
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
# Load iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Use only class 0 and 1
X = X[y != 2]
y = y[y != 2]


In [ ]:
# Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [ ]:
# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
# Train logistic regression model
log_model = LogisticRegression()
log_model.fit(X_train, y_train)


In [ ]:
# Predict on test set
y_pred = log_model.predict(X_test)


In [ ]:
# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


In [ ]:
# Visualize confusion matrix
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, cmap="Greens", fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()


*Naive Baise*

In [ ]:
# Import libraries
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
# Load Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target


In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [ ]:
# Feature scaling (optional)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
# Create and train the Naive Bayes model
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)


In [ ]:
# Predict on the test set
y_pred = nb_model.predict(X_test)


In [ ]:
# Evaluation metrics
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


In [ ]:
# Plot confusion matrix
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, cmap="Purples", fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Naive Bayes")
plt.show()
